name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [test]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            if [ ! -d ~/github-actions-kubernetes-masterclass ]; then
              git clone -b $BRANCH ${{ github.server_url }}/${{ github.repository }}.git ~/github-actions-kubernetes-masterclass
            fi
            cd ~/github-actions-kubernetes-masterclass
              git checkout $BRANCH
              git pull origin $BRANCH

             cat > .env <<EOF
              MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
              DB_HOST=${{ secrets.DB_HOST }}
              DB_PORT=${{ secrets.DB_PORT }}
              DB_USER=${{ secrets.DB_USER }}
              DB_PASSWORD=${{ secrets.DB_PASSWORD }}
              DB_NAME=${{ secrets.DB_NAME }}
              DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
              EOF

            # Stop old containers safely
            docker compose down || true

            # Remove dangling containers/images
            docker container prune -f || true
            docker image prune -af || true

            # Pull latest images
            docker compose pull || true

            # Build and start containers
            docker compose up -d --build --remove-orphans

            # Cleanup
            docker system prune -f || true

            # Show running containers
            docker ps
