name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  deploy:
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'test'

    runs-on: ubuntu-latest
    environment:
         name: production
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
         
          script: |
            set -euo pipefail
          
            export BRANCH=test
          
            APP_DIR="$HOME/github-actions-kubernetes-masterclass"
          
            echo "===== STARTING DEPLOYMENT ====="
          
            if [ ! -d "$APP_DIR" ]; then
              git clone -b $BRANCH \
              https://github.com/${{ github.repository }}.git \
              $APP_DIR
            fi
          
            cd $APP_DIR
          
            git fetch origin
          
            git checkout $BRANCH
          
            git reset --hard origin/$BRANCH
          
            echo "===== CREATING ENV FILE ====="
          
            printf "%s\n" \
            "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" \
            "DB_HOST=${{ secrets.DB_HOST }}" \
            "DB_PORT=${{ secrets.DB_PORT }}" \
            "DB_USER=${{ secrets.DB_USER }}" \
            "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
            "DB_NAME=${{ secrets.DB_NAME }}" \
            "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" \
            > .env
          
            cat .env
          
            echo "===== STOPPING OLD CONTAINERS ====="
          
            docker compose down || true
          
            echo "===== PULLING IMAGES ====="
          
            docker compose pull || true
          
            echo "===== STARTING CONTAINERS ====="
          
            docker compose up -d
          
            echo "===== CLEANUP ====="
          
            docker image prune -af || true
          
            echo "===== RUNNING CONTAINERS ====="
          
            docker ps
          
            echo "===== DEPLOYMENT SUCCESS ====="
