name: Hackathon CI CD

on:
    push:
        branches:
            - test
    workflow_dispatch:
permissions:
    contents: write

jobs:
    CI:
        name: CI Pipeline
        uses:  ./.github/workflows/ci.yml
        secrets: inherit

    manifest-bump:
        needs: CI
        uses: ./.github/workflows/cd-k8s.yml
        secrets: inherit
    
    deploy:
        name: Kubernetes Deployment
        needs: [manifest-bump , CI]
        uses: ./.github/workflows/cd.yml
        secrets: inherit
     
    Terraform:
        name: Terraform Infra
        uses:  ./.github/workflows/terraform_infra.yaml
        secrets: inherit
    
    
    
